name: "Release Workflow"

on:
  release:
    types: [created]

jobs:
  release: 
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Node"
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
          scope: ""
      - name: "Install PNPM"
        run: |
          npm install -g pnpm@8.15.3
          pnpm i
      - name: "Distribute"
        run: |
          npm run dist
